version: '3'

services:
  web:
    build: ./web
    command: gunicorn config.wsgi -b :8000
    volumes:
      - ./web:/teavana/web
    expose:
      - '8000'
    env_file:
      - .env
    links:
      - db

  nginx:
    build: ./nginx
    volumes:
      - ./web/collected_static:/static
      - ./web/media:/media
    ports:
      - '80:80'
    links:
      - web

  db:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
