# Generated by Django 2.0.4 on 2018-04-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tea',
            name='type',
            field=models.CharField(choices=[('black', 'Black Tea'), ('white', 'White Tea'), ('green', 'Green Tea'), ('oolong', 'Oolong tea')], default='black', max_length=6),
            preserve_default=False,
        ),
    ]
