# Generated by Django 2.0.4 on 2018-04-23 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teas', '0001_initial'),
        ('orders', '0002_auto_20180423_0453'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
                ('tea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teas.Tea')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
