# Generated by Django 2.0.4 on 2018-04-23 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('address_line_1', models.CharField(max_length=64)),
                ('address_line_2', models.CharField(blank=True, max_length=16, null=True)),
                ('city', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=32)),
                ('zipcode', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
